version: "3.8"
services:
  es1:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.10.1
    volumes:
      - type: bind
        source: ./elasticsearch/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - /elastic:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=TRDCSRVELP001
      - discovery.seed_hosts=TRDCSRVELP002
      - cluster.initial_master_nodes=TRDCSRVELP001,TRDCSRVELP002
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${ES_HEAP_SIZE:-2g} -Xmx${ES_HEAP_SIZE:-2g}"
      - ELASTIC_PASSWORD=E!s!39-k4=8
      - xpack.security.enabled=true
      # - xpack.security.transport.ssl.enabled=true
      # - xpack.security.transport.ssl.verification_mode= certificate
      # - xpack.security.transport.ssl.keystore.path= elastic-certificates.p12
      # - xpack.security.transport.ssl.truststore.path= elastic-certificates.p12
    ulimits:
      memlock:
        soft: -1
        hard: -1
    network_mode: "host"
  es2:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.10.1
    volumes:
      - type: bind
        source: ./elasticsearch/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - /elastic:/usr/share/elasticsearch/data
    environment:
      - node.name=TRDCSRVELP002
      - discovery.seed_hosts=TRDCSRVELP001
      - cluster.initial_master_nodes=TRDCSRVELP001,TRDCSRVELP002
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${ES_HEAP_SIZE:-2g} -Xmx${ES_HEAP_SIZE:-2g}"
      - ELASTIC_PASSWORD=E!s!39-k4=8
      - xpack.security.enabled=true
      # - xpack.security.transport.ssl.enabled=true
      # - xpack.security.transport.ssl.verification_mode= certificate
      # - xpack.security.transport.ssl.keystore.path= elastic-certificates.p12
      # - xpack.security.transport.ssl.truststore.path= elastic-certificates.p12
    ulimits:
      memlock:
        soft: -1
        hard: -1
    network_mode: "host"

  # es3:
  #   build:
  #     context: elasticsearch/
  #     args:
  #       ELK_VERSION: 7.10.1
  #   volumes:
  #     - type: bind
  #       source: ./elasticsearch/elasticsearch.yml
  #       target: /usr/share/elasticsearch/config/elasticsearch.yml
  #       read_only: true
  #     - /elastic:/usr/share/elasticsearch/data
  #   environment:
  #     - node.name=elastic42
  #     - discovery.seed_hosts=TRDCSRVELP001
  #     - cluster.initial_master_nodes=TRDCSRVELP001,TRDCSRVELP002,elastic42
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms${ES_HEAP_SIZE:-2g} -Xmx${ES_HEAP_SIZE:-2g}"
  #     - ELASTIC_PASSWORD=E!s!39-k4=8
  #     - xpack.security.enabled=true
  #     # - xpack.security.transport.ssl.enabled=true
  #     # - xpack.security.transport.ssl.verification_mode= certificate
  #     # - xpack.security.transport.ssl.keystore.path= elastic-certificates.p12
  #     # - xpack.security.transport.ssl.truststore.path= elastic-certificates.p12

  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   network_mode: "host"
  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: 7.10.1
    volumes:
      - type: bind
        source: ./kibana/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD="E!s!39-k4=8"
    ports:
      - 5601:5601
    # depends_on:
    #   - TRDCSRVELP001
    #   - TRDCSRVELP002
    network_mode: "host"

  # web_server:
  #   build:
  #     context: ./nginx
  #   restart: always
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
