version: "3.8"
services:
  docker40:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.17.8
    volumes:
      - type: bind
        source: ./elasticsearch/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - /elastic:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=docker40
      - discovery.seed_hosts=docker41
      - cluster.initial_master_nodes=docker40,docker41,docker42
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${ES_HEAP_SIZE:-2g} -Xmx${ES_HEAP_SIZE:-2g}"
      - ELASTIC_PASSWORD=123456
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true

    ulimits:
      memlock:
        soft: -1
        hard: -1
    network_mode: "host"

  docker41:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.17.8
    volumes:
      - type: bind
        source: ./elasticsearch/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - /elastic:/usr/share/elasticsearch/data
    environment:
      - node.name=docker41
      - discovery.seed_hosts=docker40
      - cluster.initial_master_nodes=docker40,docker41,docker42
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${ES_HEAP_SIZE:-2g} -Xmx${ES_HEAP_SIZE:-2g}"
      - ELASTIC_PASSWORD=123456
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    network_mode: "host"

  docker42:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.17.8
    volumes:
      - type: bind
        source: ./elasticsearch/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - /elastic:/usr/share/elasticsearch/data
    environment:
      - node.name=docker42
      - discovery.seed_hosts=docker40
      - cluster.initial_master_nodes=docker40,docker41,docker42
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${ES_HEAP_SIZE:-2g} -Xmx${ES_HEAP_SIZE:-2g}"
      - ELASTIC_PASSWORD=123456
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    network_mode: "host"
  kibana2:
    build:
      context: kibana/
      args:
        ELK_VERSION: 7.17.8
    volumes:
      - type: bind
        source: ./kibana/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD="123456"
    ports:
      - 5601:5601
    # depends_on:
    #   - docker40
    #   - docker41
    network_mode: "host"

  # web_server:
  #   build:
  #     context: ./nginx
  #   restart: always
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
